services:
  telegram-workout-bot:
    env_file: "bot/.env"
    build: .
    ports:
      - "8000:8000"
  postgres:
    image: postgres:17rc1-alpine3.20
    restart: always
    ports:
      - "5432:5432"
    env_file: "database/.env.db"
    volumes:
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  postgres_data:
